create table aircrafts
(
    code     varchar(3) primary key,

    name     varchar not null,
    category char(1)
);
INSERT INTO public.aircrafts (code, name, category) VALUES ('100', 'Fokker 100', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('141', 'BAe 146-100 Pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('142', 'BAe 146-200 Pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('143', 'BAe 146-300 Pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('146', 'BAe 146 all pax models', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('14F', 'BAe 146 Freighter (-100/200/300QT & QC)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('14X', 'BAe 146 Freighter (-100QT & QC)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('14Y', 'BAe 146 Freighter (-200QT & QC)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('14Z', 'BAe 146 Freighter (-300QT & QC)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('310', 'Airbus A310 all pax models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('312', 'Airbus A310-200 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('313', 'Airbus A310-300 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('318', 'Airbus A318', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('319', 'Airbus A319', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('31F', 'Airbus A310 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('31X', 'Airbus A310-200 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('31Y', 'Airbus A310-300 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('320', 'Airbus A320-100/200', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('321', 'Airbus A321-100/200', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('32A', 'Airbus A320-200 (Sharklets)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('32B', 'Airbus A321-200 (Sharklets)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('32S', 'Airbus A318/319/320/321', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('330', 'Airbus A330 all models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('332', 'Airbus A330-200', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('333', 'Airbus A330-300', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('340', 'Airbus A340 all models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('342', 'Airbus A340-200', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('343', 'Airbus A340-300', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('345', 'Airbus A340-500', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('346', 'Airbus A340-600', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('380', 'Airbus A380 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('388', 'Airbus A380', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('38F', 'Airbus A380 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('703', 'Boeing 707-300 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('707', 'Boeing 707/720 all pax models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('70F', 'Boeing 707 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('70M', 'Boeing 707 Combi', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('717', 'Boeing 717', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('721', 'Boeing 727-100 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('722', 'Boeing 727-200 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('727', 'Boeing 727 all pax models', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('72B', 'Boeing 727-100 Mixed Configuration', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('72C', 'Boeing 727-200 Mixed Configuration', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('72F', 'Boeing 727 Freighter (-100/200)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('72M', 'Boeing 727 Combi', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('72S', 'Boeing 727-200 Advanced pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('72X', 'Boeing 727-100 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('72Y', 'Boeing 727-200 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('731', 'Boeing 737-100 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('732', 'Boeing 737-200 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('733', 'Boeing 737-300 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('734', 'Boeing 737-400 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('735', 'Boeing 737-500 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('736', 'Boeing 737-600 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('737', 'Boeing 737 all pax models', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('738', 'Boeing 737-800 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('739', 'Boeing 737-900 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73C', 'Boeing 737-300 (winglets)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73F', 'Boeing 737 all Freighter models', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73G', 'Boeing 737-700 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73H', 'Boeing 737-800 (winglets) pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73J', 'Boeing 737-900 (winglets)', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73M', 'Boeing 737-200 Combi', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73N', 'Boeing 737-300 Mixed Config', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73W', 'Boeing 737-700 (winglets) pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73X', 'Boeing 737-200 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('73Y', 'Boeing 737-300 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('741', 'Boeing 747-100 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('742', 'Boeing 747-200 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('743', 'Boeing 747-300 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('744', 'Boeing 747-400 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('747', 'Boeing 747 all pax models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74C', 'Boeing 747-200 Combi', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74D', 'Boeing 747-300 Combi', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74E', 'Boeing 747-400 Combi', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74F', 'Boeing 747 all Freighter models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74H', 'Boeing 747-8 Intercontinental', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74J', 'Boeing 747-400 (Domestic) pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74L', 'Boeing 747SP', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74M', 'Boeing 747 all Combi models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74R', 'Boeing 747SR pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74T', 'Boeing 747-100 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74U', 'Boeing 747-300 / 747-200 SUD Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74V', 'Boeing 747SR Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74X', 'Boeing 747-200 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('74Y', 'Boeing 747-400 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('752', 'Boeing 757-200 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('753', 'Boeing 757-300 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('757', 'Boeing 757 all pax models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('75F', 'Boeing 757 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('75M', 'Boeing 757 Mixed Configuration', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('75W', 'Boeing 757-200 (winglets)', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('762', 'Boeing 767-200 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('763', 'Boeing 767-300 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('764', 'Boeing 767-400 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('767', 'Boeing 767 all pax models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('76F', 'Boeing 767 all Freighter models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('76W', 'Boeing 767-300ER', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('76X', 'Boeing 767-200 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('76Y', 'Boeing 767-300 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('772', 'Boeing 777-200 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('773', 'Boeing 777-300 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('777', 'Boeing 777 all pax models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('77L', 'Boeing 777-200LR', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('77W', 'Boeing 777-300ER', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('787', 'Boeing 787 Dreamliner', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('788', 'Boeing 787-8 Dreamliner', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('A26', 'Antonov AN-26', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('A28', 'Antonov AN-28 / PZL Miele M-28 Skytruck', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('A30', 'Antonov AN-30', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('A32', 'Antonov AN-32', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('A40', 'Antonov AN-140', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('A4F', 'Antonov AN-124 Ruslan', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('A81', 'Antonov An-148-100', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AB3', 'Airbus Industrie A300 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AB4', 'Airbus Industrie A300B2/B4/C4 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AB6', 'Airbus Industrie A300-600 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ABB', 'Airbus Industrie A300-600ST Beluga Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ABF', 'Airbus Industrie A300 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ABX', 'Airbus Industrie A300C4/F4 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ABY', 'Airbus Industrie A600-600 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ACD', 'Gulfstream/Rockwell (Aero) Commander/Turbo Commander', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ACP', 'Gulfstream/Rockwell (Aero) Commander', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ACT', 'Gulfstream/Rockwell (Aero) Turbo Commander', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ALM', 'Ayres LM-200 Loadmaster', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AN4', 'Antonov AN-24', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AN6', 'Antonov AN-26 / AN-30 /AN-32', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AN7', 'Antonov AN-72 / AN-74', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ANF', 'Antonov AN-12', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('APH', 'Eurocopter (Aerospatiale) SA330 Puma / AS332 Super Puma', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AR1', 'Avro RJ100 Avroliner', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AR7', 'Avro RJ70 Avroliner', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AR8', 'Avro RJ85 Avroliner', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ARJ', 'Avro RJ70 / RJ85 / RJ100 Avroliner', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ARX', 'Avro RJX85 / RJX100', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AT4', 'Aerospatiale/Alenia ATR 42-300 / 320', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AT5', 'Aerospatiale/Alenia ATR 42-500', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AT7', 'Aerospatiale/Alenia ATR 72', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ATP', 'British Aerospace ATP', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ATR', 'Aerospatiale/Alenia ATR 42/ ATR 72', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AX1', 'Avro RJX100', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('AX8', 'Avro RJX85', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('B11', 'British Aerospace (BAC) One Eleven / RomBAC One Eleven', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('B12', 'British Aerospace (BAC) One Eleven 200', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('B13', 'British Aerospace (BAC) One Eleven 300', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('B14', 'British Aerospace (BAC) One Eleven 400/475', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('B15', 'British Aerospace (BAC) One Eleven 500 / RomBAC One Eleven', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('B72', 'Boeing 720B pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BE1', 'Beechcraft 1900/1900C/1900D', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BE2', 'Beechcraft twin piston engines', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BEC', 'Beechcraft light aircraft', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BEH', 'Beechcraft 1900D', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BEP', 'Beechcraft light aircraft - single engine', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BES', 'Beechcfrat 1900/1900C', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BET', 'Beechcraft light aircraft - twin turboprop engine', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BH2', 'Bell Helicopters', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BNI', 'Pilatus Britten-Norman BN-2A/B Islander', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BNT', 'Pilatus Britten-Norman BN-2A Mk III Trislander', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('BUS', 'Bus', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CCJ', 'Canadair Challenger', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CCX', 'Canadair Global Express', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CD2', 'Government Aircraft Factories N22B / N24A Nomad', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CL4', 'Canadair CL-44', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CN1', 'Cessna light aircraft - single piston engine', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CN2', 'Cessna light aircraft - twin piston engines', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CNA', 'Cessna light aircraft', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CNC', 'Cessna light aircraft - single turboprop engine', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CNJ', 'Cessna Citation', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CNT', 'Cessna light aircraft - twin turboprop engines', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CR1', 'Canadair Regional Jet 100', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CR2', 'Canadair Regional Jet 200', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CR7', 'Canadair Regional Jet 700', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CR9', 'Canadair Regional Jet 900', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CRA', 'Canadair Regional Jet 705', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CRJ', 'Canadair Regional Jet', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CRK', 'Canadair CRJ1000', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CRV', 'Aerospatiale (Sud Aviation) Se.210 Caravelle', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CS2', 'CASA / IPTN 212 Aviocar', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CS5', 'CASA / IPTN CN-235', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CV4', 'Convair CV-440 Metropolitan pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CV5', 'Convair CV-580 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CVF', 'Convair CV-240 / 440 / 580 / 600 / 640 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CVR', 'Convair CV-240 / 440 / 580 / 600 / 640 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CVV', 'Convair CV-240 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CVX', 'Convair CV-440 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CVY', 'Convair CV-580 / 600 / 640 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('CWC', 'Curtiss C-46 Commando', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D10', 'Douglas DC-10 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D11', 'Douglas DC-10-10/15 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D1C', 'Douglas DC-10-30/40 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D1F', 'Douglas DC-10 all Freighters', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D1M', 'Douglas DC-10 all Combi models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D1X', 'Douglas DC-10-10 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D1Y', 'Douglas DC-10-30 / 40 Freighters', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D28', 'Fairchild Dornier Do.228', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D38', 'Fairchild Dornier Do.328', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D3F', 'Douglas DC-3 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D6F', 'Douglas DC-6A/B/C Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D8F', 'Douglas DC-8 all Freighters', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D8L', 'Douglas DC-8-62 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D8M', 'Douglas DC-8 all Combi models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D8Q', 'Douglas DC-8-72 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D8T', 'Douglas DC-8-50 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D8X', 'Douglas DC-8-61 / 62 / 63 Freighters', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D8Y', 'Douglas DC-8-71 / 72 / 73 Freighters', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D91', 'Douglas DC-9-10 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D92', 'Douglas DC-9-20 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D93', 'Douglas DC-9-30 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D94', 'Douglas DC-9-40 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D95', 'Douglas DC-9-50 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D9C', 'Douglas DC-9-30 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D9F', 'Douglas DC-9 all Freighters', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('D9X', 'Douglas DC-9-10 Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DC3', 'Douglas DC-3 pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DC6', 'Douglas DC6A/B pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DC8', 'Douglas DC-8 all pax models', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DC9', 'Douglas DC-9 all pax models', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DF2', 'Dassault (Breguet Mystere) Falcon 10 / 100 / 20 / 200 / 2000', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DF3', 'Dassault (Breguet Mystere) Falcon 50 / 900', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DFL', 'Dassault (Breguet Mystere) Falcon', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DH1', 'De Havilland Canada DHC-8-100 Dash 8 / 8Q', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DH2', 'De Havilland Canada DHC-8-200 Dash 8 / 8Q', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DH3', 'De Havilland Canada DHC-8-300 Dash 8 / 8Q', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DH4', 'De Havilland Canada DHC-8-400 Dash 8Q', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DH7', 'De Havilland Canada DHC-7 Dash 7', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DH8', 'De Havilland Canada DHC-8 Dash 8 all models', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHB', 'De Havilland Canada DHC-2 Beaver / Turbo Beaver', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHC', 'De Havilland Canada DHC-4 Caribou', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHD', 'De Havilland DH.104 Dove', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHH', 'De Havilland DH.114 Heron', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHL', 'De Havilland Canada DHC-3 Turbo Otter', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHO', 'De Havilland Canada DHC-3 Otter / Turbo Otter', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHP', 'De Havilland Canada DHC-2 Beaver', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHR', 'De Havilland Canada DHC-2 Turbo-Beaver', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHS', 'De Havilland Canada DHC-3 Otter', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('DHT', 'De Havilland Canada DHC-6 Twin Otter', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('E70', 'Embraer 170', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('E75', 'Embraer EMB 175', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('E90', 'Embraer 190', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('E95', 'Embraer EMB 195', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('EM2', 'Embraer EMB.120 Brasilia', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('EMB', 'Embraer EMB.110 Bandeirnate', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('EMJ', 'Embraer 170/190', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ER3', 'Embraer RJ135', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ER4', 'Embraer RJ145 Amazon', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ERD', 'Embraer RJ140', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ERJ', 'Embraer RJ135 / RJ140 / RJ145', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('F21', 'Fokker F.28 Fellowship 1000', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('F22', 'Fokker F.28 Fellowship 2000', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('F23', 'Fokker F.28 Fellowship 3000', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('F24', 'Fokker F.28 Fellowship 4000', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('F27', 'Fokker F.27 Friendship / Fairchild F.27', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('F28', 'Fokker F.28 Fellowship', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('F50', 'Fokker 50', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('F70', 'Fokker 70', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('FA7', 'Fairchild Dornier 728JET', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('FK7', 'Fairchild FH.227', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('FRJ', 'Fairchild Dornier 328JET', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('GRG', 'Grumman G.21 Goose', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('GRJ', 'Gulfstream Aerospace G-1159 Gulfstream II / III / IV / V', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('GRM', 'Grumman G.73 Turbo Mallard', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('GRS', 'Gulfstream Aerospace G-159 Gulfstream I', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('H25', 'British Aerospace (Hawker Siddeley) HS.125', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('HEC', 'Helio H-250 Courier / H-295 / 385 Super Courier', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('HOV', 'Hovercraft', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('HS7', 'Hawker Siddeley HS.748', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('I14', 'Ilyushin IL114', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('I93', 'Ilyushin IL96-300 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('I9F', 'Ilyushin IL96 Freighters', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('I9M', 'Ilyushin IL96M pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('I9X', 'Ilyushin IL96-300 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('I9Y', 'Ilyushin IL96T Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('IL6', 'Ilyushin IL62', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('IL7', 'Ilyushin IL76', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('IL8', 'Ilyushin IL18', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('IL9', 'Ilyushin IL96 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ILW', 'Ilyushin IL86', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('J31', 'British Aerospace Jetstream 31', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('J32', 'British Aerospace Jetstream 32', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('J41', 'British Aerospace Jetstream 41', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('JST', 'British Aerospace Jetstream 31 / 32 / 41', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('JU5', 'Junkers Ju52/3M', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('L10', 'Lockheed L-1011 Tristar pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('L11', 'Lockheed L-1011 1 / 50 / 100 / 150 / 200 / 250 Tristar pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('L15', 'Lockheed L-1011 500 Tristar pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('L1F', 'Lockheed L-1011 Tristar Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('L49', 'Lockheed L-1049 Super Constellation', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('L4T', 'LET 410', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('LCH', 'Launch - Boat', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('LMO', 'Limousine', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('LOE', 'Lockheed L-188 Electra pax', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('LOF', 'Lockheed L-188 Electra Freighter', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('LOH', 'Lockheed L-182 / 282 / 382 (L-100) Hercules', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('LOM', 'Lockheed L-188 Electra Mixed Configuration', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('LRJ', 'Gates Learjet', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M11', 'McDonnell Douglas MD11 pax', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M1F', 'McDonnell Douglas MD11 Freighter', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M1M', 'McDonnell Douglas MD11 Mixed Configuration', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M80', 'McDonnell Douglas MD80', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M81', 'McDonnell Douglas MD81', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M82', 'McDonnell Douglas MD82', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M83', 'McDonnell Douglas MD83', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M87', 'McDonnell Douglas MD87', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M88', 'McDonnell Douglas MD88', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('M90', 'McDonnell Douglas MD90', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('MBH', 'Eurocopter (MBB) Bo.105', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('MD9', 'MD Helicopters MD900 Explorer', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('MIH', 'MIL Mi-8 / Mi-17 / Mi-171 / Mil-172', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('MU2', 'Mitsubishi Mu-2', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('ND2', 'Aerospatiale (Nord) 262', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('NDC', 'Aerospatiale SN.601 Corvette', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('NDE', 'Eurocopter (Aerospatiale) AS350 Ecureuil / AS355 Ecureuil 2', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('NDH', 'Eurocopter (Aerospatiale) SA365C / SA365N Dauphin 2', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('PA1', 'Piper light aircraft - single piston engine', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('PA2', 'Piper light aircraft - twin piston engines', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('PAG', 'Piper light aircraft', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('PAT', 'Piper light aircraft - twin turboprop engines', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('PL2', 'Pilatus PC-12', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('PL6', 'Pilatus PC-6 Turbo Porter', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('PN6', 'Partenavia P.68', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('RFS', 'Road Feeder Service - Cargo Truck', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('S20', 'Saab 2000', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('S58', 'Sikorsky S-58T', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('S61', 'Sikorsky S-61', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('S76', 'Sikorsky S-76', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('SF3', 'Saab SF340A/B', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('SH3', 'Shorts SD.330', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('SH6', 'Shorts SD.360', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('SHB', 'Shorts SC-5 Belfast', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('SHS', 'Shorts SC-7 Skyvan', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('SSC', 'Aerospatiale/BAC Concorde', 'H');
INSERT INTO public.aircrafts (code, name, category) VALUES ('SU9', 'Sukhoi Superjet 100-95', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('SWM', 'Fairchild (Swearingen) SA26 / SA226 / SA227 Metro / Merlin / Expediter', 'L');
INSERT INTO public.aircrafts (code, name, category) VALUES ('T20', 'Tupolev Tu-204 / Tu-214', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('TRN', 'Train', ' ');
INSERT INTO public.aircrafts (code, name, category) VALUES ('TU3', 'Tupolev Tu134', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('TU5', 'Tupolev Tu154', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('VCV', 'Vickers Viscount', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('WWP', 'Israel Aircraft Industries 1124 Westwind', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('YK2', 'Yakovlev Yak 42', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('YK4', 'Yakovlev Yak 40', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('YN2', 'Harbin Yunshuji Y12', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('YN7', 'Xian Yunshuji Y7', 'M');
INSERT INTO public.aircrafts (code, name, category) VALUES ('YS1', 'NAMC YS-11', 'M');